export const AnalyticsScreen = {
  ONBOARDING_WELCOME: 'onboarding_welcome',
  ONBOARDING_GOALS: 'onboarding_goals',
  ONBOARDING_SCHEDULE: 'onboarding_schedule',
  ONBOARDING_HABITS: 'onboarding_habits',
  ONBOARDING_NOTIFICATIONS: 'onboarding_notifications',
  ONBOARDING_COMPLETE: 'onboarding_complete',
  HOME_DASHBOARD: 'home_dashboard',
  HABIT_DETAIL: 'habit_detail',
  HABIT_CREATE: 'habit_create',
  HABIT_EDIT: 'habit_edit',
  STACK_DETAIL: 'stack_detail',
  STACK_CREATE: 'stack_create',
  STACK_FLOW: 'stack_flow',
  AI_INSIGHTS: 'ai_insights',
  AI_COACHING: 'ai_coaching',
  AI_SUGGESTIONS: 'ai_suggestions',
  PROGRESS_OVERVIEW: 'progress_overview',
  PROGRESS_WEEKLY: 'progress_weekly',
  PROGRESS_CHARTS: 'progress_charts',
  SETTINGS: 'settings',
  SETTINGS_NOTIFICATIONS: 'settings_notifications',
  SETTINGS_ACCOUNT: 'settings_account',
  SETTINGS_EXPORT: 'settings_export',
  PAYWALL: 'paywall',
  SUBSCRIPTION_MANAGE: 'subscription_manage',
} as const;

export type AnalyticsScreenName = typeof AnalyticsScreen[keyof typeof AnalyticsScreen];
